# Generated by Django 3.1.7 on 2021-03-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0004_blog_field1'), ('blog', '0005_blog_field2')]

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='field1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='field2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
