# Generated by Django 3.1.7 on 2021-03-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_field3'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='field4',
            field=models.CharField(default='', max_length=255),
        ),
    ]
