# Generated by Django 3.1.7 on 2021-03-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_field5'),
        ('blog', '0007_blog_field6'),
    ]

    operations = [
    ]
